In [46]:
import numpy as np

ARRAY OPERATION

ARITHMETIC OPERATION

In [47]:
a1 = np.array([1, 2, 3, 4])
a2 = np.array([5, 6, 7, 8])
a2

array([5, 6, 7, 8])

In [48]:
a1 + a2 # size must be same in both array

array([ 6,  8, 10, 12])

In [49]:
a1 - a2 
a1 * a2
a1 / a2 

array([0.2       , 0.33333333, 0.42857143, 0.5       ])

VECTORIZED MATH FUNCTION

In [50]:
a1 + 1    # directly perfrom the opertion on the array
a2 - 1
a2 ** 2

array([25, 36, 49, 64])

In [51]:
array = np.array([1, 2, 3])  # sq root
array = np.sqrt(array)
array

array([1.        , 1.41421356, 1.73205081])

In [52]:
array = np.round(array) # round
array = np.ceil(array)  # round up
array = np.floor(array) # round down
array

array([1., 1., 2.])

In [53]:
arr = np.pi
arr

3.141592653589793

In [54]:
radi = np.array([1, 2, 3])  
print(np.pi * radi ** 2)

[ 3.14159265 12.56637061 28.27433388]


COMPARISON OPERATORS

In [55]:
scores = np.array([91, 55, 100, 73, 82, 64]) 
print(scores == 100) # highest
print(scores > 35)  # pass
print(scores < 35)  # fail

#give ans as bool

[False False  True False False False]
[ True  True  True  True  True  True]
[False False False False False False]


BROADCASTING 

allows  numpy to perfrom op on array with diff shapes by virtually expanding shape
Only work if number is same or one should be 1

In [56]:
arr1 = np.array([[1], [2], [3], [4]])
arr2 = np.array([[1, 2, 3, 4]])   # 2d array with single row
print(arr1.shape)
print(arr2.shape)

(4, 1)
(1, 4)


In [57]:
arr3 = arr1 + arr2  # both have 1 so we can perfrom broadcasting but cant do if 1 is not their because 4 dont match
arr3

array([[2, 3, 4, 5],
       [3, 4, 5, 6],
       [4, 5, 6, 7],
       [5, 6, 7, 8]])

FILTERING

In [58]:
ages = np.array([[21, 17, 19, 20, 19, 65],
                 [39, 22, 15, 99, 20, 21]])


In [59]:
teen = ages[ages < 18]
adult = ages[(ages > 18) & (ages < 65) ] # and operator
print(teen)
print(adult)

[17 15]
[21 19 20 19 39 22 20 21]


In [60]:
adult = np.where(ages >= 18, ages, 0) # it retain the exact shape of array , condition, array, value at the place were condition not true so 0
adult

array([[21,  0, 19, 20, 19, 65],
       [39, 22,  0, 99, 20, 21]])