In [95]:
import numpy as np

**Valid Sudoku**

In [96]:
s = np.array([
    [5, 3, 4, 6, 7, 8, 9, 1, 2],
    [6, 7, 2, 1, 9, 5, 3, 4, 8],
    [1, 9, 8, 3, 4, 2, 5, 6, 7],
    
    [8, 5, 9, 7, 6, 1, 4, 2, 3],
    [4, 2, 6, 8, 5, 3, 7, 9, 1],
    [7, 1, 3, 9, 2, 4, 8, 5, 6],
    
    [9, 6, 1, 5, 3, 7, 2, 8, 4],
    [2, 8, 7, 4, 1, 9, 6, 3, 5],
    [3, 4, 5, 2, 8, 6, 1, 7, 9]
])

In [97]:
# sum of each row
a = np.sum(s,axis= 0)
for rows in a :
  if rows != 45 :
    print("not valid sudoku: ")
    break
else :
  print("valid sudoku")

valid sudoku


In [98]:
# sum of each column
a = np.sum(s,axis= 1)
for cloumn in a :
  if cloumn != 45 :
    print("not valid sudoku: ")
    break
else :
  print("valid sudoku")

valid sudoku


In [99]:
# check the sum in 3*3 matrix should be equal to 45

for rows in range(0, 9, 3) :
  for col in range(0, 9, 3) :
    a = np.sum(s[rows: rows + 3, col : col + 3])
    if( a != 45) :
      print("sudoku not valid: ")
      break
else :
  print("sudoku valid")

sudoku valid


**General Questions**

In [100]:
import numpy as np

# Columns: [Age, Math Marks, Science Marks]
data = np.array([
    [18, 85, 78],   # Student 1
    [19, 92, 88],   # Student 2
    [17, 76, 95],   # Student 3
    [18, 65, 70],   # Student 4
    [20, 90, 85]    # Student 5
])

In [101]:
#Get the shape of the matrix.
data.shape

(5, 3)

In [102]:
#Find the average age of students.
np.mean(data[:,0])  # select every row and 0th cloumn , give exact value the one you want to select , in slicing the last value should be +1 

np.float64(18.4)

In [103]:
#Extract Math marks of all students.
a = data[:, 1]
print(a)

[85 92 76 65 90]


In [104]:
#Find the highest Science mark.
high = np.max(data[:,2])
print(high)

95


In [105]:
#Get details of the student who scored more than 90 in Math.
index = 0
for i in data[:, 1] :
  if i > 90 :
    print(f"Student {index} score more than 90")
  index = index + 1

    

Student 1 score more than 90


In [106]:
#Increase Math marks of all students by 5.
for  index, marks in enumerate(data[:, 1]) :
  data[index, 1] = marks + 5 

print(data)
print(" ")

# another way

data[:,1] += 5
print(data)
 

[[18 90 78]
 [19 97 88]
 [17 81 95]
 [18 70 70]
 [20 95 85]]
 
[[ 18  95  78]
 [ 19 102  88]
 [ 17  86  95]
 [ 18  75  70]
 [ 20 100  85]]


In [107]:
#Find how many students are younger than 19.
for student, age in enumerate(data[:, 0]) :
  if age < 19 :
    print(f"Student {student} is younger than 19")


Student 0 is younger than 19
Student 2 is younger than 19
Student 3 is younger than 19


In [111]:
#Calculate the average marks in each subject (column-wise mean).
avg = np.mean(data[:, 1:], axis=1)
print(avg)

[86.5 95.  90.5 72.5 92.5]


In [114]:
#Get data of students who scored at least 80 in both subjects.
data[(data[:, 1] >= 80) & (data[:, 2] >= 80)]


array([[ 19, 102,  88],
       [ 17,  86,  95],
       [ 20, 100,  85]])

In [122]:
#Replace all Science marks < 75 with 0.
data[data[:,2] < 75, 2] = 0
data


array([[ 18,  95,  78],
       [ 19, 102,  88],
       [ 17,  86,  95],
       [  0,   0,   0],
       [ 20, 100,  85]])