In [11]:
import numpy as np

In [12]:
arr = np.arange(11, 21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [13]:
# ALL SLICING OPERTION ARE SAME AS PYTHON

arr[1 : 6]   # STARTING INDEX = 0, ENDING INDEX = END + 1


array([12, 13, 14, 15, 16])

In [14]:
# NUMPY INDEXI NG AND SLICING OF MATRIX

In [15]:
arr = np.arange(1, 37).reshape(6,6)
arr

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36]])

In [16]:
arr[1,3]  # ACESS ELEMENT IN MATRIX

np.int64(10)

In [17]:
slice = arr[0:2, 1:3] # multiple element from rows and column
slice

array([[2, 3],
       [8, 9]])

In [18]:
arr[3:6 , 3:5]

array([[22, 23],
       [28, 29],
       [34, 35]])

In [19]:
arr[3:6 , 3:6]

array([[22, 23, 24],
       [28, 29, 30],
       [34, 35, 36]])

In [20]:
arr[3:6 , 3:6]

array([[22, 23, 24],
       [28, 29, 30],
       [34, 35, 36]])