In [18]:
import numpy as np

In [19]:
arr = np.arange(11, 21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [20]:
# ALL SLICING OPERTION ARE SAME AS PYTHON

arr[1 : 6]   # STARTING INDEX = 0, ENDING INDEX = END + 1


array([12, 13, 14, 15, 16])

In [21]:
# NUMPY INDEXI NG AND SLICING OF MATRIX

In [22]:
arr = np.arange(1, 31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [23]:
arr[1,3]  # ACESS ELEMENT IN MATRIX

np.int64(9)

In [29]:
slice = arr[0:2, 1:3] # multiple element from rows and column
slice

array([[2, 3],
       [7, 8]])

In [32]:
arr[3:6 , 3:5]

array([[19, 20],
       [24, 25],
       [29, 30]])