In [1]:
import numpy as np

In [2]:
b = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
arr = np.array(b)
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [3]:
arr = np.arange(1, 10, 2) # 1 se 0 tak no print kro aur 2 ke gap ke sath
arr

array([1, 3, 5, 7, 9])

In [4]:
arr = np.zeros((6,6))
arr

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [5]:
arr = np.ones((4, 6))
arr

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [6]:
arr = np.linspace(1, 5, 3) # 1 se 5 ke bich mai 3 evenly space wale number
arr

array([1., 3., 5.])

In [7]:
np.random.rand(10)  # n ramdom numbers {values betwn 0 - 1)

array([0.73453238, 0.06896187, 0.03337157, 0.28052989, 0.70167119,
       0.62117593, 0.48027492, 0.98357644, 0.13522055, 0.32181541])

In [8]:
np.random.randn(10) # -3 se 3 tak values

array([-1.16420067,  0.04269002,  1.27456908, -1.05087375,  0.5116693 ,
        2.61456022,  0.19690041,  0.79960028,  0.6953641 ,  0.06425183])

In [9]:
np.random.randint(6) # o se 6 ke bich random int
np.random.randint(10,20,6) # 10 se 20 tak 6 random integer


array([18, 19, 10, 15, 19, 12], dtype=int32)

In [15]:
# ARRAY ATTRIBUTE

arr = np.array([[1, 2, 3], [4,5,6], [7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [16]:
arr.shape   # attribute(variable) isliye () nhi lagaya

(3, 3)

In [17]:
arr.size

9

In [18]:
arr.dtype


dtype('int64')

In [19]:
# ARRAY METHODS

In [20]:
arr.min()  # method(function) isliye ()

np.int64(1)

In [21]:
arr.max()

np.int64(9)

In [24]:
arr.sum()

np.int64(45)

In [25]:
np.sum(arr, axis = 0)  # SUM COLUMN WISE 

array([12, 15, 18])

In [27]:
np.sum(arr, axis = 1)  # SUM ROW WISE 

array([ 6, 15, 24])

In [28]:
arr.mean()
arr.std()

np.float64(2.581988897471611)

In [29]:
arr.argmin()  # INDEX AT WHICH MIN ELEMENT IS PRESENT

np.int64(0)

In [30]:
arr.argmax()  # INDEX AT WHICH MIN ELEMENT IS PRESENT

np.int64(8)

In [33]:
# RESHAPE AND RESIZE

In [41]:
arr = np.arange(1, 31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [43]:
arr = arr.reshape(6,5)   # the matrix should aslo contain 30 element , the size should be equal to the array , resize = reshape stored into the same varible you used
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])